# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-12 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
