# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 09:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20170323_1031'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='nta',
            new_name='not_billable',
        ),
        migrations.AddField(
            model_name='report',
            name='absence_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='employment.AbsenceType'),
        ),
        migrations.AddField(
            model_name='report',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='tracking.Activity'),
        ),
    ]
