# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_absence_comment'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['date'], name='tracking_re_date_8770c2_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['start_datetime'], name='tracking_ac_start_d_c43640_idx'),
        ),
    ]
