# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tracking", "0002_auto_20170912_1346")]

    operations = [
        migrations.RenameField(
            model_name="activityblock", old_name="from_datetime", new_name="from_time"
        ),
        migrations.RenameField(
            model_name="activityblock", old_name="to_datetime", new_name="to_time"
        ),
    ]
