# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20170518_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityblock',
            name='from_datetime',
            field=models.DateTimeField(),
        ),
    ]
