# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-04 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20170501_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.Task'),
        ),
    ]
