# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("tracking", "0004_auto_20171005_1057")]

    operations = [migrations.RemoveField(model_name="absence", name="duration")]
