# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-10 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("tracking", "0005_remove_absence_duration")]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="transferred",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="activity",
            name="from_time",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="activity",
            name="to_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
