# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 08:45
from __future__ import unicode_literals

from datetime import timedelta
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def migrate_absences_forwards(apps, schema_editor):
    Report  = apps.get_model('tracking', 'Report')
    Absence = apps.get_model('tracking', 'Absence')

    for report in Report.objects.filter(absence_type__isnull=False):
        Absence.objects.get_or_create(
            user=report.user,
            date=report.date,
            defaults={
                'type': report.absence_type,
                'duration': report.duration
            }
        )

def migrate_absences_reverse(apps, schema_editor):
    Report  = apps.get_model('tracking', 'Report')
    Absence = apps.get_model('tracking', 'Absence')

    for absence in Absence.objects.all():
        Report.objects.create(
            user=absence.user,
            date=absence.date,
            type=absence.absence_type,
            duration=absence.duration
        )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employment', '0003_absencetype_fill_worktime'),
        ('tracking', '0005_auto_20170504_1259'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.DurationField(default=timedelta())),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employment.AbsenceType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='absence',
            unique_together=set([('date', 'user')]),
        ),
        migrations.RunPython(
            migrate_absences_forwards,
            migrate_absences_reverse
        ),
        migrations.RemoveField(
            model_name='report',
            name='absence_type',
        ),
    ]
