# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 08:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("tracking", "0008_delete_activity_blocks")]

    operations = [migrations.RemoveField(model_name="report", name="activity")]
