# Generated by Django 2.2.15 on 2020-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0012_migrate_report_review_false"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="billed",
            field=models.BooleanField(default=False),
        ),
    ]
