# Generated by Django 3.2.13 on 2022-06-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0013_report_billed"),
    ]

    operations = [
        migrations.RenameField(
            model_name="absence",
            old_name="type",
            new_name="absence_type",
        ),
    ]
