# Generated by Django 3.2.13 on 2022-08-02 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0015_report_rejected"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="remaining_effort",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
