# Generated by Django 3.2.16 on 2023-02-09 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0016_report_remaining_effort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="remaining_effort",
            field=models.DurationField(default=datetime.timedelta(0), null=True),
        ),
    ]
