# Generated by Django 3.1.7 on 2021-08-03 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0012_migrate_reviewers_to_assignees"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="reviewers",
        ),
    ]
