# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("tracking", "0003_auto_20170912_1347")]

    operations = [
        migrations.AlterField(
            model_name="activity", name="date", field=models.DateField()
        )
    ]
