# Generated by Django 2.2.10 on 2020-03-06 11:18

from django.db import migrations


def migrate_report_review(apps, schema_editor):
    Report = apps.get_model("tracking", "Report")
    Report.objects.filter(review=True).exclude(verified_by__isnull=True).update(
        review=False
    )


class Migration(migrations.Migration):
    dependencies = [("tracking", "0011_auto_20181026_1528")]

    operations = [migrations.RunPython(migrate_report_review)]
