# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("employment", "0007_auto_20170911_0959")]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=30, verbose_name="last name"),
        )
    ]
