# Generated by Django 3.1.7 on 2021-04-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employment", "0013_auto_20210302_1136"),
    ]

    operations = [
        migrations.AddField(
            model_name="employment",
            name="is_external",
            field=models.BooleanField(default=False),
        ),
    ]
