# Generated by Django 3.2.16 on 2022-11-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0015_remaining_effort_task_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sent_at", models.DateTimeField(null=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("budget_check_30", "project budget exceeded 30%"),
                            ("budget_check_70", "project budget exceeded 70%"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
