# Generated by Django 2.2.10 on 2020-04-07 18:52

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [("subscription", "0003_auto_20170907_1151")]

    operations = [
        migrations.AlterField(
            model_name="package",
            name="price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2, default_currency="CHF", max_digits=7
            ),
        )
    ]
