# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-06 14:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20171010_1423'),
        ('subscription', '0003_auto_20170907_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True, verbose_name='password')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Customer')),
            ],
        ),
    ]
