# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supervisors',
            field=models.ManyToManyField(related_name='supervisees', to=settings.AUTH_USER_MODEL),
        ),
    ]
