# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("employment", "0002_auto_20170823_1051")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tour_done",
            field=models.BooleanField(default=False),
        )
    ]
