# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 12:03
from __future__ import unicode_literals

from django.db import migrations
import timed.employment.models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_user_supervisors'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', timed.employment.models.UserManager()),
            ],
        ),
    ]
