# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-08 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20170323_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencetype',
            name='fill_worktime',
            field=models.BooleanField(default=False),
        ),
    ]
