# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0002_auto_20170512_1317'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employment',
            index=models.Index(fields=['start_date', 'end_date'], name='employment__start_d_74c274_idx'),
        ),
        migrations.AddIndex(
            model_name='publicholiday',
            index=models.Index(fields=['date'], name='employment__date_2d002c_idx'),
        ),
    ]
