# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20170808_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAbsenceType',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('employment.absencetype',),
        ),
        migrations.RemoveField(
            model_name='absencecredit',
            name='duration',
        ),
        migrations.AddField(
            model_name='absencecredit',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
