# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20170808_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAbsenceType',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('employment.absencetype',),
        ),
        migrations.RemoveField(
            model_name='absencecredit',
            name='duration',
        ),
        migrations.AddField(
            model_name='absencecredit',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='absencecredit',
            name='days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
