# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0003_auto_20170808_1403'),
        ('employment', '0004_auto_20170809_1647'),
    ]

    operations = [
    ]
