# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [("employment", "0004_auto_20170904_1510")]

    operations = [
        migrations.AddField(
            model_name="employment",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employment",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
