# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("employment", "0005_auto_20170906_1259")]

    operations = [
        migrations.AlterField(
            model_name="overtimecredit",
            name="duration",
            field=models.DurationField(default=datetime.timedelta(0)),
        )
    ]
