# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("employment", "0008_auto_20171013_1041")]

    operations = [migrations.DeleteModel(name="UserAbsenceType")]
