# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employment', '0009_delete_userabsencetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimecredit',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
