# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-26 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("employment", "0011_auto_20171101_1227")]

    operations = [
        migrations.AlterField(
            model_name="absencecredit",
            name="absence_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="employment.AbsenceType"
            ),
        ),
        migrations.AlterField(
            model_name="employment",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employments",
                to="employment.Location",
            ),
        ),
    ]
