# Generated by Django 3.1.7 on 2021-03-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employment", "0012_auto_20181026_1528"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
