# Generated by Django 3.1.7 on 2021-09-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("employment", "0014_employment_is_external"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_accountant",
            field=models.BooleanField(default=False),
        ),
    ]
