# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-19 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['name', 'archived'], name='projects_ta_name_dd9620_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name', 'archived'], name='projects_cu_name_e0e97a_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['name', 'archived'], name='projects_pr_name_ac60a8_idx'),
        ),
    ]
