# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projects", "0002_auto_20170823_1045")]

    operations = [
        migrations.AlterModelOptions(name="customer", options={"ordering": ["name"]}),
        migrations.AlterModelOptions(name="project", options={"ordering": ["name"]}),
        migrations.AlterModelOptions(name="task", options={"ordering": ["name"]}),
        migrations.AlterModelOptions(
            name="tasktemplate", options={"ordering": ["name"]}
        ),
    ]
