# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-20 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [("projects", "0007_project_subscription_project")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="billing_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="projects.BillingType",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="cost_center",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="projects.CostCenter",
            ),
        ),
    ]
