# Generated by Django 2.2.15 on 2020-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_auto_20201201_1412"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="billed",
            field=models.BooleanField(default=False),
        ),
    ]
