# Generated by Django 3.1.7 on 2021-11-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_remove_project_reviewers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerassignee",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectassignee",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="taskassignee",
            name="is_customer",
            field=models.BooleanField(default=False),
        ),
    ]
