# Generated by Django 3.2.13 on 2022-08-04 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0014_add_is_customer_role_to_assignees"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="remaining_effort_tracking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="total_remaining_effort",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="task",
            name="most_recent_remaining_effort",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
