# Generated by Django 3.2.16 on 2022-12-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("budget_check_30", "project budget exceeded 30%"),
                    ("budget_check_70", "project budget exceeded 70%"),
                    ("changed_employment", "recently changed employment"),
                    ("reviewers_unverified", "reviewer has reports to verify"),
                    (
                        "supervisors_shorttime",
                        "supervisor has supervisees with short time",
                    ),
                    ("notify_accountants", "notify accountats"),
                ],
                max_length=50,
            ),
        ),
    ]
